package com.geo.source.git;

/**
 * @author YanZhen
 * @date 2020/04/24 09:03
 **/
public class Test2 {
    public static void main(String[] args) {
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！18");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！46");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！64");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
        System.out.println("替换类测试！");
    }
}
