spring:
  application:
    name: demo
  jackson:
    time-zone: GMT+8
  servlet:
    multipart: #上传文件配置
      max-file-size: 20MB # 设置文件大小 不限制-1
      max-request-size: 20MB # 设置请求大小 不限制-1

management:
  endpoints:
    jmx:
      exposure:
        include: 123456
    web:
      exposure:
        include: 123456
  server:
    port: 8081 # Actuator Web 访问端口
  endpoint:
    health:
      show-details: always
# spring cloud access&secret config
# 可以访问如下地址查看: https://usercenter.console.aliyun.com/#/manage/ak
#alibaba.cloud.access-key=****
#alibaba.cloud.secret-key=****

# 应用服务 WEB 访问端口
server:
  port: 8080



